sudo: false
language: python

python:
  - 3.6

install:
  - pip install "Nikola[extras]" doctr

script:
  - set -e
  - nikola build
  - doctr deploy . --built-docs output/


env:
  global:
    # Doctr deploy key for carlosperezm/blog
    - secure: "CEzH3TAgaSm95dTjTyvgR7r0lMirlF1nqYQQNC1mw9cCg08KDkX3WA2g2BUfzEqdCXmrKpKDGBDaGSJKVvWUMHssfl37n3uZEfTvmqc+NImnYp3aVQ0xLC/9dPSyn1xnvKMRiv3iadV0lZYj0YEiS3VT8Te+UpdxtMQ/u0J/I1cj/7VgAp4ORr9/hwx3d3BmOJZ3tY9VY9VXK7/2nbSZA1LSmNQrRDQirnrwb1dNe6sk5cpGE51SWu4oeB/9b4wMws7D7JkHDGo7JCE+srhB04uuhbgTUaronU8I3/wB2/Yf1dvIHVMt1WbSoXFurNv0Zp/KqE4veAO2aOYHx0vCSSI57bBbbJnzPLYR7S5Vhkx3CNuyCMp8ERPPgO/vI6k8FlL85lylDFAkox9XhGEd1imawWGo6CdAUQa2u3mBpdptqXybecMb8HZgcTvz95EgJozlZxOyQXmeVWG3H2f7aCCucuYsqUYXtutyqLXPZBbqXNFjzvVkETpZvjTxcT2F1MUfEaQMdlwWXglzDSyRZnnuMEMX72OrFvw4nuugCmdy9haO7DHvbLmOK3WpfIKN44VfyTfbGY+0RCMJACVx79FOW94VvPhJVbz6d1rmHVPRFKjiJMFllum/C7iQhFvapvApVBX7Tnr2mw3lZgxi+o/9HW6+Vm+c9OPeOG59c/U="

